"""phase 1 schema

Revision ID: f0efc554ed36
Revises: 57300b8c3643
Create Date: 2026-09-07 17:49:13.052390

Replaces the demo title/content `documents` table with the real ingestion
schema: `documents` becomes a file entity, and `parent_chunks` /
`child_chunks` hold the text. Written by hand rather than autogenerated:
autogenerate diffs column-by-column and would try to ALTER `documents.id`
from integer to uuid in place, which is not what is happening here -- the
whole entity's meaning changed, not one column's type. There is no
production data to preserve, so this drops and recreates `documents`
outright.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'f0efc554ed36'
down_revision: Union[str, Sequence[str], None] = '57300b8c3643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_table("documents")

    op.create_table(
        "documents",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("sha256_hash", sa.String(length=64), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("status", sa.Text(), server_default="QUEUED", nullable=False),
        sa.Column("stage", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failed_stage", sa.Text(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256_hash", name="uq_documents_sha256_hash"),
        # The closed set every later stage task writes: QUEUED through
        # DEAD_LETTER. Enforced here, not only by convention in application
        # code, so a typo status string fails the write instead of sitting
        # silently in the column.
        sa.CheckConstraint(
            "status IN ("
            "'QUEUED', 'PARSING', 'STRUCTURING', 'ENRICHING', 'EMBEDDING', "
            "'PERSISTING', 'COMPLETED', 'RETRYING', 'DEAD_LETTER'"
            ")",
            name="ck_documents_status",
        ),
    )

    op.create_table(
        "parent_chunks",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("document_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("page_start", sa.Integer(), nullable=False),
        sa.Column("page_end", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], ondelete="CASCADE"
        ),
        sa.UniqueConstraint(
            "document_id", "chunk_index", name="uq_parent_chunks_document_id_chunk_index"
        ),
    )
    op.create_index(
        "ix_parent_chunks_document_id", "parent_chunks", ["document_id"]
    )

    op.create_table(
        "child_chunks",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("document_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("parent_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("contextualized", sa.Text(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        # Width fixed at migration time -- see child_chunk.py for why this
        # does not read EMBED_DIMENSIONS from settings.
        sa.Column("embedding", Vector(1536), nullable=False),
        sa.Column("category", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["parent_chunks.id"], ondelete="CASCADE"
        ),
        # No standalone index on document_id: the unique constraint below
        # already is a composite index led by document_id, and Postgres can
        # use a composite index's leading column alone (leftmost-prefix).
        sa.UniqueConstraint(
            "document_id", "chunk_index", name="uq_child_chunks_document_id_chunk_index"
        ),
    )
    op.create_index("ix_child_chunks_parent_id", "child_chunks", ["parent_id"])

    # Autogenerate cannot infer an HNSW index -- this is why the migration
    # is hand-written even for the parts a diff tool could otherwise manage.
    # vector_ip_ops (inner product) is only equivalent to cosine distance
    # because S4 L2-normalises every embedding before it is stored; an
    # un-normalised vector under this operator class would rank nonsense.
    op.execute(
        "CREATE INDEX ix_child_chunks_embedding_hnsw ON child_chunks "
        "USING hnsw (embedding vector_ip_ops) WITH (m = 16, ef_construction = 64)"
    )
    # Partial: most rows settle into COMPLETED or DEAD_LETTER and are never
    # queried by status again, so indexing them would only cost writes.
    op.execute(
        "CREATE INDEX ix_documents_active_status ON documents (status) "
        "WHERE status NOT IN ('COMPLETED', 'DEAD_LETTER')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_documents_active_status")
    op.execute("DROP INDEX IF EXISTS ix_child_chunks_embedding_hnsw")

    op.drop_table("child_chunks")
    op.drop_table("parent_chunks")
    op.drop_table("documents")

    # Restore the demo table exactly as migration 57300b8c3643 created it.
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(1536), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
