"""Build the six sample PDFs. Run: uv run python tests/fixtures/generate.py

Output must be reproducible bit-for-bit: these six files are committed, so if
every run produced different bytes, git would report a phantom binary diff
whenever anyone ran the generator. Hence reportlab's invariant=1 and the
stripped metadata on the scan -- both embed a timestamp by default.

Generated by script rather than taken from real PDFs: reproducible, small,
free of licensing questions, and adding a new case means editing this file
instead of going to ask someone for a document.
"""

from pathlib import Path

import pymupdf
from pypdf import PdfReader, PdfWriter
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import BaseDocTemplate, Frame, PageTemplate, Paragraph, Table

HERE = Path(__file__).parent
STYLES = getSampleStyleSheet()
BODY = (
    "Doanh thu quy 3 nam 2024 dat 41.7 ty dong, tang 12 phan tram so voi cung ky. "
    "Chi phi van hanh giu nguyen o muc 8.2 ty dong. "
)


def _simple(path: Path, flowables, page_size=A4):
    doc = BaseDocTemplate(str(path), pagesize=page_size, invariant=1)
    frame = Frame(50, 50, page_size[0] - 100, page_size[1] - 100, id="f")
    doc.addPageTemplates([PageTemplate(id="t", frames=[frame])])
    doc.build(flowables)


def clean_text():
    _simple(HERE / "clean_text.pdf", [Paragraph(BODY * 6, STYLES["Normal"]) for _ in range(3)])


def tables():
    data = [["Quy", "Doanh thu", "Chi phi"], ["Q1", "38.1", "8.0"], ["Q2", "39.4", "8.1"]]
    _simple(HERE / "tables.pdf", [Paragraph(BODY, STYLES["Normal"]), Table(data)])


def multi_column():
    path = HERE / "multi_column.pdf"
    doc = BaseDocTemplate(str(path), pagesize=A4, invariant=1)
    left = Frame(50, 50, 230, 700, id="l")
    right = Frame(300, 50, 230, 700, id="r")
    doc.addPageTemplates([PageTemplate(id="two", frames=[left, right])])
    doc.build([Paragraph(BODY * 4, STYLES["Normal"]) for _ in range(4)])


def scanned():
    """Render clean_text to images and rewrap them, losing the text layer.

    JPEG rather than PNG: 244 KiB instead of 3.4 MB for the same pages, and
    it is what a real scanner produces anyway. dpi 150 so OCR still has
    something to work with in tasks 12 and 13.
    """
    src = pymupdf.open(HERE / "clean_text.pdf")
    out = pymupdf.open()
    for page in src:
        pix = page.get_pixmap(dpi=150)
        new = out.new_page(width=page.rect.width, height=page.rect.height)
        new.insert_image(new.rect, stream=pix.tobytes("jpg", jpg_quality=85))
    # set_metadata clears the creation date; no_new_id stops MuPDF writing a
    # fresh random trailer /ID. Both are needed, and the /ID is the one that
    # only shows up if you compare runs more than a second apart.
    out.set_metadata({})
    out.save(HERE / "scanned.pdf", no_new_id=1)


def encrypted():
    reader = PdfReader(HERE / "clean_text.pdf")
    writer = PdfWriter()
    for page in reader.pages:
        writer.add_page(page)
    writer.encrypt("s1mple")
    with open(HERE / "encrypted.pdf", "wb") as fh:
        writer.write(fh)


def malformed():
    """Keep the PDF header, cut away almost all of the body.

    Truncating to 60%, the intuitive choice, does NOT corrupt the file: MuPDF
    rescans the objects and rebuilds the xref, so it still opens. The cut has
    to go deep enough that no object survives intact. Verified right here
    after writing, so that if clean_text.pdf ever changes size this fails
    loudly instead of silently weakening a test six tasks later.
    """
    data = (HERE / "clean_text.pdf").read_bytes()
    path = HERE / "malformed.pdf"
    path.write_bytes(data[:128])
    try:
        pymupdf.open(path)
    except pymupdf.FileDataError:
        return
    raise RuntimeError("malformed.pdf still opens -- cut it deeper")


def main() -> None:
    clean_text()
    tables()
    multi_column()
    scanned()
    encrypted()
    malformed()
    print("6 fixtures generated in", HERE)


if __name__ == "__main__":
    main()
